Fix podspec so that it can validate.
This fixes the following error message received when we tried to install this in
an expo project running Expo SDK 50.
```
[!] The `react-native-payments` pod failed to validate due to 1 error:
    - ERROR | source: Unable to validate due to exception: undefined method `=~' for an instance of Hash
```

<!-- ps-id: d5f62f23-b57a-43f0-882f-bf013394f75a -->